/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rjxgcbuhqvegcycibtpi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqeGdjYnVocXZlZ2N5Y2lidHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MDQ3NjYsImV4cCI6MjA4NzM4MDc2Nn0.xneYDwS-a1hP-igKH-TEdvcvioQl1GBUVoRnKM33DOU"